import turtle
import random
bg = turtle.Screen()
bg.bgcolor("pink")
tommy = turtle.Turtle()
tommy.shape("turtle")
tommy.speed(2)
def line(x1, y1, x2, y2, color, pensize):
  tommy.penup()
  tommy.goto(x1, y1)
  tommy.color(color)
  tommy.pensize(pensize)
  tommy.pendown()
  tommy.goto(x2, y2)
  tommy.penup()
snow_colors = ["white", "blue", "silver", "light yellow", "light blue",  "purple", "grey", "magenta", 'green', 'orange', 'gold', 'red', 'red']
line(-190, -180, 190, -180, random.choice(snow_colors), 6)
line(-160, -150, 160, -150, random.choice(snow_colors), 6)
line(-130, -120, 130, -120, random.choice(snow_colors), 6)
tommy.goto(-70,-110)
tommy.begin_fill()
tommy.pendown()
tommy.color("black")
tommy.goto(50,-110)
tommy.left(90)
tommy.forward(60)
tommy.left(90)
tommy.forward(125)
tommy.left(90)
tommy.forward(60)
tommy.penup()
tommy.end_fill()
def candle(x, color):
  tommy.goto(x, -40)
  tommy.color(color)
  tommy.pendown()
  tommy.pensize(3)
  tommy.goto(x, -20)
  tommy.penup()
candle(-60, random.choice(snow_colors))
candle(-40, random.choice(snow_colors))
candle(-20, random.choice(snow_colors))
candle(0, random.choice(snow_colors))
candle(20, random.choice(snow_colors))
candle(40, random.choice(snow_colors))
tommy.goto(-200, 30)
tommy.color("dark blue")
tommy.pendown()
tommy.write("Happy Birthday!",None, None, "150pt bold")
tommy.penup()
tommy.goto(-250, 250)
tommy.mainloop()